# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    jdkVersionOption: '1.17'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'

- script: |
    echo "Listing files in app/build/outputs/apk/debug:"
    ls -la app/build/outputs/apk/debug
  displayName: 'List APK files'

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/app/build/outputs/apk/debug
    contents: '**/*.apk'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SkipcartAPK'
    publishLocation: 'Container'